// Copyright 2012 The Gorilla Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sessions

import (
	"net/http"
	"time"
)

const (
	NilSID = "NIL"
)

// Session --------------------------------------------------------------------

// NewSession is called by session stores to create a new session instance.
func NewSession(store Store, name string) *Session {
	return &Session{
		Values:  make(map[interface{}]interface{}),
		store:   store,
		name:    name,
		Options: new(Options),
	}
}

// Session stores the values and optional configuration for a session.
type Session struct {
	// The ID of the session, generated by stores. It should not be used for
	// user data.
	ID string
	// Values contains the user-data for the session.
	Values       map[interface{}]interface{}
	Options      *Options
	IsNew        bool
	isOutputOnly byte
	store        Store
	name         string
}

// Save is a convenience method to save this session. It is the same as calling
// store.Save(request, response, session). You should call Save before writing to
// the response or returning from the handler.
func (s *Session) Save(r *http.Request, w http.ResponseWriter) error {
	return s.store.Save(r, w, s)
}

// Name returns the name used to register the session.
func (s *Session) Name() string {
	return s.name
}

// Store returns the session store used to register the session.
func (s *Session) Store() Store {
	return s.store
}

func (s *Session) IsOutputOnly() byte {
	return s.isOutputOnly
}

func (s *Session) EnableOutputOnly(enable byte) {
	s.isOutputOnly = enable
}

func (s *Session) HasExpired() bool {
	if s.Options == nil {
		return false
	}
	if s.Options.MaxAge < 0 {
		return true
	}
	if expires := s.Options.Expires; !expires.IsZero() && !expires.After(time.Now()) {
		return true
	}
	return false
}
